import 'package:flutter/material.dart';

const kMainColor = Color(0xFFFFC12F);
const kSecondryColor = Color(0xFFFFECAC);
const kUnActiveColor = Color(0xFFC1BDB8);
const kProductName = "productName";
const kProductPrice = "productPrice";
const kProductDescription = "productDescription";
const kProductLocation = "productLocation";
const kProductCategory = "productCategory";
const kProductCollection = "products";
const kJackets = "jackets";
const kTrousers = "trousers";
const kTshirts = "t-shirts";
const kShoes = "shoes";
const kOrders = "Orders";
const kOrderDetails = "OrderDetails";
const kTotalPrice = "TotalPrice";
const kAddress = "Address";
const kProductQuantity = "Quantity";
